---
- name: Restart php-fpm
  ansible.builtin.service:
    name: "php{{ php_version }}-fpm"
    state: restarted

- name: Reload php-fpm
  ansible.builtin.service:
    name: "php{{ php_version }}-fpm"
    state: reloaded
